### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by kaishijeng** [Maratyszcza/NNPACK#71]
I am arm-a53 processor running at 64bit-ubuntu16.04
Does NNPACK support this platform?

Thanks,

**Comment by Maratyszcza** [comment]
NNPACK can be compiled for this platform, but didn't test the build scripts on it. Please try following the [Building](https://github.com/Maratyszcza/NNPACK#building) section in README, and if something breaks, let me know.

**Comment by kaishijeng** [comment]
I got the following error:
Traceback (most recent call last):
  File "./configure.py", line 5, in <module>
    parser = confu.standard_parser()

    AttributeError: 'module' object has no attribute 'standard_parser'

I end up to use nnpack-rpi with minor adjustment, but the performance is
not good

Thanks,

**Comment by Maratyszcza** [comment]
@kaishijeng You either have a very old version of `confu`, or didn't install it with `[sudo] pip install --upgrade git+https://github.com/Maratyszcza/confu`

**Comment by kaishijeng** [comment]
I am not able to do pip install --upgrade git+https://github.com/
Maratyszcza/confu because there is an error below:


  Cloning https://github.com/Maratyszcza/confu to /tmp/pip-WOIk9F-build
    Complete output from command python setup.py egg_info:
    CRITICAL:root:failed to detect the host platform: sys.platform =
linux2, platform.machine = aarch64
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-WOIk9F-build/setup.py", line 3, in <module>
        from confu import __version__, __maintainer__, __email__
      File "confu/__init__.py", line 35, in <module>
        from confu.platform import Platform
      File "confu/platform.py", line 217, in <module>
        host = Platform(detect_host())
      File "confu/platform.py", line 213, in detect_host
        .format(sys=sys, machine=machine))
  *  ValueError: Unexpected sys.platform, platform.machine combination
(linux2, aarch64)*

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-WOIk9F-build/

**Comment by Maratyszcza** [comment]
I pushed a commit to `confu` that is supposed to fix it. Please try `[sudo] pip install --upgrade git+https://github.com/Maratyszcza/confu` again.

**Comment by kaishijeng** [comment]
confu installation works now. However, I have encountered the following
error during configuration.py:

Configuring dependency pthreadpool
Traceback (most recent call last):
  File "./configure.py", line 396, in <module>
    main(sys.argv[1:]).generate()
  File "./configure.py", line 36, in main
    (build.deps.pthreadpool, build.deps.fxdiv, build.deps.fp16): any,
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/deps.py", line
45, in __getattr__
    reload(configure)
UnboundLocalError: local variable 'reload' referenced before assignment

**Comment by Maratyszcza** [comment]
It was regression introduced by an unrelated patch earlier today. Should be fixed now.

**Comment by kaishijeng** [comment]
Thanks for updates and NNPACK compiles OK. Just curious, will compilation
flags be optimized for aarch64-neon instructions?

Thanks,

**Comment by Maratyszcza** [comment]
I just pushed a commit to NNPACK to make it use ARM NEON intrinsics for ARM64 build. Please test.

**Comment by kaishijeng** [comment]
I pull in your latest changes and use caffe2 to do benchmark between Eigen
and NNPACK. It surprises me that Eigen performs better (See below)::

./caffe2/python/convnet_benchmarks.py --batch_size 1 --model Inception
--forward_only --cpu  --num_workers 4
I0423 00:37:20.150459  8441 net_dag.cc:558] Main run finished. Milliseconds
per iter: 358.717. Iters per second: 2.78771

./caffe2/python/convnet_benchmarks.py --batch_size 1 --model Inception
--forward_only --cpu  --num_workers 4 --engine NNPACK
I0423 00:38:59.354216  8446 net_dag.cc:558] Main run finished. Milliseconds
per iter: 1235.55. Iters per second: 0.809358

Could NNPACK not be optimized for aarch64-neon?

**Comment by Maratyszcza** [comment]
@kaishijeng It should help to manually specify NNPACK algorithms in convolutional layers. Default options are skewed towards large networks (e.g. VGG) and/or large image size (e.g. for HD-image segmentation/style transfer/superresolution).

cc @Yangqing

**Comment by aidamanzano** [comment]
Hi I'm using a Raspbery Pi 4 with Raspbian Buster OS, I tried what you mentioned further up in the thread and ran `[sudo] pip install --upgrade git+https://github.com/Maratyszcza/confu` and then when I run `python ./configure.py` 
I still get this error: `Traceback (most recent call last):
  File "./configure.py", line 5, in <module>
    parser = confu.standard_parser()
AttributeError: module 'confu' has no attribute 'standard_parser'`

Im following this [tutorial](https://funofdiy.blogspot.com/2018/08/deep-learning-with-raspberry-pi-real.html) and using this fork https://github.com/shizukachan/NNPACK

**Comment by Maratyszcza** [comment]
@aidamanzano Please don't use confu, it is deprecated. Build NNPACK with CMake (see README for details).
